### ISSUE TITLE
Difference between scylla-cdc-java and debezium-connector-cassandra

### ISSUE THREAD

**Issue by pkgonan** [scylladb/scylla-cdc-java#22]
Hi.

What is difference between this project and [debezium-connector-cassandra](https://github.com/debezium/debezium-connector-cassandra).

**Comment by avelanarius** [comment]
First, a similarity: both Scylla CDC Source Connector and debezium-connector-cassandra are source connectors (ingesting data from database to Kafka) and both are based on Debezium framework.

The difference is in implementation of CDC in Cassandra and Scylla.

[Cassandra's CDC](https://cassandra.apache.org/doc/latest/operating/cdc.html) is saving the CDC log into files on each Cassandra node. Therefore, debezium-connector-cassandra must be installed on each Cassandra node and it reads local files on each node.

In contrast, [Scylla's CDC](https://docs.scylladb.com/using-scylla/cdc/cdc-intro/) saves the CDC log into a normal CQL table. Querying the CDC log can be done by normal CQL queries - no need to read local files on each node. Therefore, Scylla CDC Source Connector is run separately (on Kafka Connect cluster) and is scaled separately to Scylla.

Cassandra and Scylla CDC implementations are not compatible, meaning you can't use debezium-connector-cassandra for Scylla and Scylla CDC Source Connector for Cassandra.

**Comment by pkgonan** [comment]
@avelanarius 
Thanks for the detailed explanation.

So, if we use scyllaDB, i think we need to use the scylla-cdc-java connector. 

I would like to ask you last two questions. 

First. Currently, can the scylla-cdc-java connector be used in production?
Second. If our scyllaDB cluster size is 3, what is the appropriate tasks.max size? is that 3 right ?

**Comment by avelanarius** [comment]
> First. Currently, can the scylla-cdc-java connector be used in production?

Currently we provide the connector in the "preview" phase. We are now starting a [Confluent "Gold verification"](https://www.confluent.io/verified-integrations-program/) process after which we would consider the connector production-ready (unfortunately, I can't provide a specific date for that yet).
 
> Second. If our scyllaDB cluster size is 3, what is the appropriate tasks.max size? is that 3 right ?

Number of tasks is more related to the number of Kafka (Connect) nodes. 

For example, if you had a Kafka cluster with 3 nodes (and each of them running Kafka Connect) and set `tasks.max` to 3, each Kafka Connect node would ingest CDC log into Kafka (each reading 1/3 of it). In our testing, we did not find that increasing `tasks.max` to a number greater than the number of Kafka Connect nodes improved the performance further (but it also did not hurt the performance).

The good news is that you could change the `tasks.max` value with small interruption: change it in configuration, restart the connector and the connector will resume from the last position.

Regarding the number of Kafka nodes you would need to use for connector to Scylla cluster of certain size, there is no single easy answer (it depends on whether the Scylla load is more read or write-heavy, size of rows, chosen Kafka serialization format, etc.)
