### ISSUE TITLE
Support scylla-cdc-kafka-connect maven repository

### ISSUE THREAD

**Issue by pkgonan** [scylladb/scylla-cdc-java#32]
Hi.

I can not find scylla-cdc-kafka-connect at maven repository. (https://mvnrepository.com/artifact/com.scylladb)
It seems very inconvenient if someone tries to use that kafka connector.

You have to manually download the project and extract the jar file to get the fat jar file. (https://github.com/scylladb/scylla-cdc-java/tree/master/scylla-cdc-kafka-connect#building-from-source)

**Comment by avelanarius** [comment]
Good point. We will provide pre-built jar/zip packages and downloads via Maven and Confluent Hub in the future.

**Comment by avelanarius** [comment]
We did some organizational cleanup of connector. It is now moved to a separate repo: https://github.com/scylladb/scylla-cdc-source-connector (the same source code as before). I have added pre-built JAR/zip packages and published it into Maven.

**Comment by pkgonan** [comment]
@avelanarius 
Thank you very much!!
