### ISSUE TITLE
Too many heartbeat message produce to kafka

### ISSUE THREAD

**Issue by pkgonan** [scylladb/scylla-cdc-java#33]
Hi.

There are too many heartbeat event produced to kafka.

[Options]
```
curl -f -i -X PUT -H "Accept:application/json" -H "Content-Type:application/json" ${cdc_url}/connectors/block_db_connector/config -d '{
  "connector.class": "com.scylladb.cdc.debezium.connector.ScyllaConnector",
  "tasks.max": "3",
  "scylla.cluster.ip.addresses": "'${database_url}'",
  "scylla.user": "'${database_user}'",
  "scylla.password": "'${database_password}'",
  "scylla.name": "cdc-data.block",
  "scylla.table.names": "'${table_include_list}'",
  "scylla.query.time.window.size": "2000",
  "scylla.confidence.window.size": "2000",
  "producer.override.acks": "-1",
  "producer.override.max.in.flight.requests.per.connection": "1",
  "producer.override.compression.type": "snappy",
  "producer.override.linger.ms": "50",
  "producer.override.batch.size": "327680",
  "errors.tolerance": "all",
  "errors.log.enable": "true",
  "errors.log.include.messages": "true",
  "topic.creation.default.replication.factor": "'${replication_factor}'",
  "topic.creation.default.partitions": "11"
}'
```

[Result]
* See __debezium-heartbeat.cdc-data.block topic. 
* We did not create, modify, or delete any rows of scyllaDB. 
* But, **384 Message per seconds!!**
<img width="1360" alt="스크린샷 2021-04-01 오후 10 12 28" src="https://user-images.githubusercontent.com/15858772/113300311-bccdfd00-9338-11eb-9440-b3cd101464ea.png">
<img width="1400" alt="스크린샷 2021-04-01 오후 10 27 17" src="https://user-images.githubusercontent.com/15858772/113300950-7036f180-9339-11eb-865f-07a755abe2f8.png">

[Questions]
1. Is it necessary processing sending heartbeat event to kafka ?
2. It's a single partition processing, so I think kafka partition offset overflow will happen soon. How to not send heartbeat to Kafka?
3. What happens if I don't send heartbeat to Kafka?
4. Is the reason for the high number of heartbeats sent to Kafka related to the scylla.query.time.window.size setting?
5. How do I solve this problem?

**Comment by avelanarius** [comment]
>1. Is it necessary processing sending heartbeat event to kafka ?

We use heartbeats in our connector to track the progress of reading CDC log. If there is a [generation change](https://docs.scylladb.com/using-scylla/cdc/cdc-stream-generations/) (new nodes added or removed in Scylla cluster), those heartbeats are necessary to determine if we have finished reading the old generation (data before a Scylla node was added/removed).

The reason behind there being so many heartbeats, is that we track this progress per each vnode (there are 256 vnodes per each Scylla node) - that many heartbeats are produced.

There is a `heartbeat.interval.ms` configuration, which determines how often those heartbeats are produced. Unfortunately, there was a bug that if `scylla.query.time.window.size` was smaller than `heartbeat.interval.ms`, then those heartbeats were produced at that rate (not `heartbeat.interval.ms`). 

In this Pull Request, I have fixed it: https://github.com/scylladb/scylla-cdc-java/pull/34. It should be merged relatively soon.

By default, `heartbeat.interval.ms` is set to 30 seconds, so the amount of heartbeats produced will be reduced by a factor of 15x (by not using `scylla.query.time.window.size` - 2 seconds). Note that after a topology change of Scylla (adding/removing Scylla nodes), there could be a temporary lag of `heartbeat.interval.ms` - how long it takes to learn about progress of CDC reading workers. 

> 2. It's a single partition processing, so I think kafka partition offset overflow will happen soon. How to not send heartbeat to Kafka?

Given that the Kafka offset is a 64-bit integer, I don't think that overflow could happen soon. (Even if it was a 1000 node Scylla cluster and heartbeat configured to be produced each second, according to my calculations it would still take 1 million+ years for a 64-bit counter to overflow)

Regarding the throughput, it would require having a 1000-node Scylla cluster and heartbeats produced each second to reach 10MB/s writes to this topic (single partition).

However, if writing to a single partition is a problem, I am open to fixing it.

> 3. What happens if I don't send heartbeat to Kafka?

Then after a Scylla topology change, the connector would not recognize that reading the old data (before topology change) has finished and it would never read the new data (after topology change)

> 4. Is the reason for the high number of heartbeats sent to Kafka related to the scylla.query.time.window.size setting?

Right now it is related, but PR https://github.com/scylladb/scylla-cdc-java/pull/34 changes it to be directly related to `heartbeat.interval.ms`.

> 5. How do I solve this problem?

Once https://github.com/scylladb/scylla-cdc-java/pull/34 PR is merged, the problem should be mitigated (writing less heartbeats with the default 30-second `heartbeat.interval.ms`). One additional thing you could consider (to reduce storage size), is to make `__debezium-heartbeat` topic retention time shorter.

**Comment by pkgonan** [comment]
@avelanarius 
Thank you for your reply :)

**Comment by avelanarius** [comment]
A fix to limit how often those heartbeat messages are produced was merged (controllable by `heartbeat.interval.ms` property, by default 30 seconds). We did some organizational cleanup - the connector is now in the separate repo: https://github.com/scylladb/scylla-cdc-source-connector. Prebuilt artifacts/Maven release contains this fix.
