### ISSUE TITLE
Large memory usage of Scylla CDC Source Connector in spiky workloads

### ISSUE THREAD

**Issue by andre-lfa** [scylladb/scylla-cdc-java#79]
One of our customers brought up an issue regarding large memory usage with CDC connector:

> Hi, we are having memory issues when using the scylla-cdc-java lib. When our pod is restarting, the lib is polling all the cdc table. There is a few millions messages in that table.
We found that unanswered issue on the github https://github.com/scylladb/scylla-cdc-java/issues/46. Do you guys have any update or solutions to this to better use resources instead of vertically scaling the pod?

> What we were expecting is that the lib was paginating under the hood and that the page size could be configurable. If we know our pod cannot handle more than 100k messages in memory, we could control it.
When the pod restart, it polls the whole cdc table reprocessing data that was processed. Our system can handle that but the pod can’t handle a few million messages in memory and the lib doesn’t seem to mitigate that use case.

I've checked with @avelanarius and the issue seems to be that it's paginating (10k) by default. But it's reading the CDC stream concurrently and every concurrent read has that 10k paging, so there's 10k * concurrency many rows in memory at one time.

cc @noellymedina @avelanarius

**Comment by andre-lfa** [comment]
@avelanarius @mykaul Hey guys, any news regarding this? Is there an ETA to fix/improve it?

**Comment by avelanarius** [comment]
Mitigated by https://github.com/scylladb/scylla-cdc-java/pull/81
